<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fons.cloud.ai</groupId>
        <artifactId>fons4ai-agent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>fons4ai-springai-starter</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.fons.cloud.ai</groupId>
            <artifactId>fons4ai-agent-common</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud.ai</groupId>
            <artifactId>fons4ai-common-tools</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-agent-framework</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>mcp</artifactId>
                    <groupId>io.modelcontextprotocol.sdk</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${springboot.version}</version>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-mcp-client</artifactId>
        </dependency>
    </dependencies>

</project>
