server:
  port: 8080

spring:
  application:
    name: ai-example
  ai:
    openai:
      api-key: sk-e629a44396154f1ba569cc7e437e41d7
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
          maxTokens: 5000
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3-vl:4b
    dashscope:
      api-key: sk-e629a44396154f1ba569cc7e437e41d7

langchain4j:
  open-ai:
    streaming-chat-model:
      api-key: sk-e629a44396154f1ba569cc7e437e41d7
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
      model-name: qwen3.5-flash
    chat-model:
      api-key: sk-e629a44396154f1ba569cc7e437e41d7
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
      model-name: qwen3.5-flash